name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Build site
        run: |
          # If you have build steps (e.g. npm install/build), add here
          # For static HTML, you can skip this step

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' # path to your built site or static files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
